BUILD_DIR ?= build
DIST_DIR ?= dist

################################################################################

LIB_DIR := lib
LIB_CPP := $(shell find $(LIB_DIR) -name "*.cpp")
LIB_HPP := $(shell find $(LIB_DIR) -name "*.hpp")
LIB_OBJ := $(addprefix $(BUILD_DIR)/lib/, $(patsubst $(LIB_DIR)/%,%,$(patsubst %.cpp,%.o,$(LIB_CPP))))
LIB_DEP := $(LIB_OBJ:.o=.d)

################################################################################

# autogenerated dependencies
-include $(LIB_DEP)

################################################################################

TEST_DIR := test
TEST_CPP := $(shell find $(TEST_DIR) -name "*.cpp")
TEST_OBJ := $(addprefix $(BUILD_DIR)/test/, $(patsubst $(TEST_DIR)/%,%,$(patsubst %.cpp,%.o,$(TEST_CPP))))

TEST_BIN := $(DIST_DIR)/test

.PHONY: test
test: $(TEST_BIN)
	@./$(TEST_BIN)

$(BUILD_DIR)/%.o: %.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c -o $@ $<
	$(CXX) $(CXXFLAGS) -MF$(@:%.o=%.d) -MG -MM -MP -MT$(@:%.o=%.d) -MT$@ $<

$(TEST_BIN): $(TEST_OBJ) $(LIB_OBJ)
	@mkdir -p $(dir $(TEST_BIN))
	$(CXX) -o $@ $< -lgtest -lgtest_main

################################################################################

.PHONY: clean
clean:
	@rm -r $(BUILD_DIR)
	@rm -r $(DIST_DIR)
